# Generated by Django 5.0.1 on 2024-01-21 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='session_name', max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2024, 1, 21, 17, 42, 31, 515128, tzinfo=datetime.timezone.utc))),
                ('result', models.CharField(max_length=20)),
                ('length', models.IntegerField(default=0)),
                ('players', models.CharField(default='player1;player2;player3;player4', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='in_game_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 17, 42, 31, 515128, tzinfo=datetime.timezone.utc)),
        ),
    ]
