# Generated by Django 5.0.1 on 2024-01-21 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0002_session_player_in_game_time_player_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 18, 15, 26, 470818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 18, 15, 26, 470818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.JSONField(max_length=4),
        ),
    ]
