# Generated by Django 5.0.1 on 2024-01-21 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0005_alter_player_last_online_alter_session_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='players',
        ),
        migrations.AddField(
            model_name='session',
            name='player1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='player2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='player3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='player4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 18, 24, 3, 725298, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 18, 24, 3, 725298, tzinfo=datetime.timezone.utc)),
        ),
    ]
