# Generated by Django 5.0.1 on 2024-01-21 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0006_remove_session_players_session_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 18, 29, 36, 300859, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 18, 29, 36, 301858, tzinfo=datetime.timezone.utc)),
        ),
    ]
