# Generated by Django 5.0.1 on 2024-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0007_alter_player_last_online_alter_session_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='desc',
            new_name='gameCount',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
