# Generated by Django 5.0.1 on 2024-01-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0010_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
