# Generated by Django 5.0.1 on 2024-01-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0011_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
