# Generated by Django 5.0.1 on 2024-01-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0012_alter_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avatarImage',
        ),
    ]
