# Generated by Django 5.0.1 on 2024-01-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0013_remove_player_avatarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='player1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='player2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='player3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='player4',
            field=models.IntegerField(default=1),
        ),
    ]
